name: User-Behavior Anomaly Detection System
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 1-5'  # 6PM UTC weekdays
  push:
    branches: [ main ]
    paths:
      - 'workflows/ubad-system/**'
      - 'playbooks/**'

env:
  SLACK_ENABLED: false  # Set to true when Slack is properly configured

jobs:
  process_ubad:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          yamllint --version

      - name: Create yamllint config
        run: |
          cat << EOF > .yamllint.yml
          extends: relaxed
          rules:
            line-length: disable
            document-start: disable
          EOF

      - name: Validate YAML Syntax
        run: |
          echo "Validating YAML files..."
          if [ -d "workflows/ubad-system" ]; then
            yamllint -f colored workflows/ubad-system/ || echo "YAML validation completed"
          else
            echo "Warning: workflows/ubad-system directory not found"
          fi

      - name: Load Process Flow
        run: |
          echo "Loading UBAD process flow..."
          if [ -f "workflows/ubad-system/process_flow.yml" ]; then
            cat workflows/ubad-system/process_flow.yml
            echo "Process flow loaded successfully"
          else
            echo "Warning: Process flow file not found!"
          fi

  execute_playbooks:
    needs: process_ubad
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playbook: ['isolate_host', 'kill_process', 'memory_dump']
      fail-fast: false  # Continue other playbooks if one fails

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "playbooks/requirements.txt" ]; then
            pip install -r playbooks/requirements.txt
          else
            echo "No requirements.txt found - skipping dependency installation"
          fi

      - name: Create dummy log file
        run: |
          mkdir -p playbooks/logs
          echo "$(date) - Starting ${{ matrix.playbook }}" > playbooks/logs/${{ matrix.playbook }}.log

      - name: Run Playbook
        run: |
          if [ -f "playbooks/${{ matrix.playbook }}.py" ]; then
            echo "Running ${{ matrix.playbook }} playbook..."
            python playbooks/${{ matrix.playbook }}.py \
              --env production \
              --log-level INFO >> playbooks/logs/${{ matrix.playbook }}.log 2>&1
            echo "Playbook execution completed"
          else
            echo "Warning: Playbook not found: ${{ matrix.playbook }}.py"
            echo "Skipping execution" >> playbooks/logs/${{ matrix.playbook }}.log
          fi

      - name: Slack Notification
        if: always() && env.SLACK_ENABLED == 'true'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          slack-message: |
            *UBAD Execution Report*
            • Playbook: ${{ matrix.playbook }}
            • Status: ${{ job.status }}
            • Run: ${{ github.run_id }}
            • Commit: ${{ github.sha }}
            • Logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  post_execution:
    needs: execute_playbooks
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Find and archive logs
        run: |
          echo "Checking for log files..."
          mkdir -p artifact_logs
          find playbooks/logs -name "*.log" -exec cp {} artifact_logs/ \;
          find workflows/ubad-system -name "*.yml" -exec cp {} artifact_logs/ \;
          ls -la artifact_logs/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()  # Always run
        with:
          name: ubad-logs-${{ github.run_id }}
          path: artifact_logs/*
          retention-days: 7

      - name: Cleanup workspace
        run: |
          echo "Cleaning up workspace..."
          rm -rf playbooks/logs
          rm -rf artifact_logs
