name: User-Behavior Anomaly Detection System
on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 18 * * 1-5'  # 6PM UTC weekdays (business hours review)
  push:
    branches: [ main ]
    paths: 
      - 'workflows/ubad-system/**'
      - 'playbooks/**'

jobs:
  process_ubad:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      security-events: write
      actions: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Validate YAML Syntax
        run: |
          echo "Validating YAML files..."
          find workflows/ubad-system -name "*.yml" -exec yamllint {} \;
        env:
          YAMLLINT_CONFIG_FILE: .yamllint.yml
          
      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Load Process Flow
        id: load_flow
        run: |
          echo "Loading UBAD process flow..."
          cat workflows/ubad-system/process_flow.yml

  execute_playbooks:
    needs: process_ubad
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playbook: ['isolate_host', 'kill_process', 'memory_dump']
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r playbooks/requirements.txt
          
      - name: Run ${{ matrix.playbook }} Playbook
        run: |
          python playbooks/${{ matrix.playbook }}.py \
            --env production \
            --log-level INFO
            
      - name: Notify SOC Team
        uses: slackapi/slack-github-action@v1.24.0
        if: always()
        with:
          channel-id: 'SOC_ALERTS'
          slack-message: |
            *UBAD Playbook Execution Result*
            Playbook: ${{ matrix.playbook }}
            Status: ${{ job.status }}
            Run ID: ${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  post_execution:
    needs: execute_playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: ubad-logs
          path: |
            playbooks/*.log
            workflows/ubad-system/*.yml
