name: User-Behavior Anomaly Detection System
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 1-5'  # 6PM UTC weekdays
  push:
    branches: [ main ]
    paths:
      - 'workflows/ubad-system/**'
      - 'playbooks/**'

jobs:
  process_ubad:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      security-events: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Create yamllint config
        run: |
          cat << EOF > .yamllint.yml
          extends: relaxed
          rules:
            line-length: disable
          EOF

      - name: Validate YAML Syntax
        run: |
          echo "Validating YAML files..."
          yamllint -f colored workflows/ubad-system/

      - name: Load Process Flow
        run: |
          echo "Loading UBAD process flow..."
          if [ -f "workflows/ubad-system/process_flow.yml" ]; then
            cat workflows/ubad-system/process_flow.yml
          else
            echo "Process flow file not found!"
            exit 1
          fi

  execute_playbooks:
    needs: process_ubad
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playbook: ['isolate_host', 'kill_process', 'memory_dump']
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "playbooks/requirements.txt" ]; then
            pip install -r playbooks/requirements.txt
          fi

      - name: Run Playbook
        run: |
          if [ -f "playbooks/${{ matrix.playbook }}.py" ]; then
            python playbooks/${{ matrix.playbook }}.py \
              --env production \
              --log-level INFO
          else
            echo "Playbook not found: ${{ matrix.playbook }}.py"
            exit 1
          fi

      - name: Slack Notification
        if: always()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL }}
          slack-message: |
            *UBAD Execution Report*
            • Playbook: ${{ matrix.playbook }}
            • Status: ${{ job.status }}
            • Run: ${{ github.run_id }}
            • Commit: ${{ github.sha }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  post_execution:
    needs: execute_playbooks
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: ubad-logs-${{ github.run_id }}
          path: |
            playbooks/*.log
            workflows/ubad-system/*.yml
          retention-days: 7
