name: User-Behavior Anomaly Detection System
on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 18 * * 1-5'  # 6PM UTC weekdays (business hours review)
  push:
    branches: [ main ]
    paths: 
      - 'workflows/ubad-system/**'
      - 'playbooks/**'

jobs:
  process_ubad:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      security-events: write
      actions: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Validate YAML Syntax
        uses: redhat-actions/yaml-validator@v1
        with:
          file: workflows/ubad-system/process_flow.yml
          
      - name: Load Process Flow
        id: load_flow
        run: |
          echo "Loading UBAD process flow..."
          yq eval workflows/ubad-system/process_flow.yml
        env:
          YQ_VERSION: 4.30.8
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install yq
        run: |
          sudo apt-get update && sudo apt-get install -y yq

  execute_playbooks:
    needs: process_ubad
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playbook: ['isolate_host', 'kill_process', 'memory_dump']
    steps:
      - uses: actions/checkout@v4
      
      - name: Run ${{ matrix.playbook }} Playbook
        run: |
          python3 -m pip install -r playbooks/requirements.txt
          python3 playbooks/${{ matrix.playbook }}.py \
            --env production \
            --log-level INFO
            
      - name: Notify SOC Team
        uses: rtCamp/action-slack-notify@v2
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
          SLACK_TITLE: "UBAD ${{ matrix.playbook }} Execution"
          SLACK_MESSAGE: "Status: ${{ job.status }}\nRun: ${{ github.run_id }}"
