name: User-Behavior Anomaly Detection System
on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 18 * * 1-5'  # 6PM UTC weekdays (business hours review)
  push:
    branches: [ main ]
    paths: 
      - 'workflows/ubad-system/**'
      - 'playbooks/**'

jobs:
  process_ubad:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      security-events: write
      actions: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Validate YAML
        uses: actions/check-yaml@v1
        with:
          files: workflows/ubad-system/process_flow.yml
          
      - name: Load Process Flow
        id: load_flow
        run: |
          echo "Loading UBAD process flow..."
          cat workflows/ubad-system/process_flow.yml
          
      - name: Notify SOC Team
        if: always()
        uses: actions/slack@v1
        with:
          payload: |
            {
              "text": "UBAD workflow executed: ${{ github.run_id }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*UBAD Process Flow Initiated*\nExecution ID: ${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  execute_playbooks:
    needs: process_ubad
    runs-on: ubuntu-latest
    strategy:
      matrix:
        playbook: ['isolate_host', 'kill_process', 'memory_dump']
    steps:
      - name: Run ${{ matrix.playbook }} Playbook
        run: |
          python3 playbooks/${{ matrix.playbook }}.py \
            --env production \
            --log-level INFO
